### ISSUE TITLE
Plans to post code?

### ISSUE THREAD

**Issue by xhevahir** [betaveros/riffshuffle#1]
Hi, I've been reading up on Songsmith and was excited to learn that your project seems to have improved on it, particularly since Songsmith has been mothballed. Do you still have any plans to publish the code?

**Comment by betaveros** [comment]
Oops haha, I had plans but put them off indefinitely due to some combination of "ugh this code and design is so bad" and "will anybody other than me really every look at or use this?"

I probably won't find the time or motivation to make the code *good* in the short term, but it still seems to work and it wasn't as hard as I feared to script all the data fetching.

**Comment by xhevahir** [comment]
Awesome! Originally I was trying to automate Songsmith to get around some bugs, but, as I eventually discovered more limitations to that program, I figured it would be better to try and implement some of it myself starting from [this one](https://github.com/flothesof/SongCreator). (Microsoft have just closed the discussion forum as well, after 10+ years.) Since that project is only the beginnings of a Songsmith replacement, and I'm only a hobbyist, with little programming and no ML training--I'm no judge of whether your code is messy or not, by the way!--that was going to be a tall order. So I'm really glad to see your work. Since I only found it last night, I've got a lot of reading to do. Thank you!

Cheers, Wade
